// src/data/pricingData.js
const pricingData = [
  {
    id: 1,
    title: "Free Pack",
    price: "$0",
    period: "Month",
    features: [
      "5 GB Storage",
      "100 GB Bandwidth",
      "1 Domain",
      "No Support",
      "24x7 Support",
      "1 User",
    ],
    buttonText: "Get Started",
    buttonDisabled: false,
  },
  {
    id: 2,
    title: "Professional Pack",
    price: "$19",
    period: "Month",
    features: [
      "50 GB Storage",
      "900 GB Bandwidth",
      "2 Domains",
      "Email Support",
      "24x7 Support",
      "5 Users",
    ],
    buttonText: "Current Plan",
    buttonDisabled: true,
    ribbon: "Popular",
  },
  {
    id: 3,
    title: "Business Pack",
    price: "$29",
    period: "Month",
    features: [
      "500 GB Storage",
      "2.5 TB Bandwidth",
      "5 Domains",
      "Email Support",
      "24x7 Support",
      "10 Users",
    ],
    buttonText: "Get Started",
    buttonDisabled: false,
  },
  {
    id: 4,
    title: "Enterprise Pack",
    price: "$49",
    period: "Month",
    features: [
      "2 TB Storage",
      "Unlimited Bandwidth",
      "50 Domains",
      "Email Support",
      "24x7 Support",
      "Unlimited Users",
    ],
    buttonText: "Get Started",
    buttonDisabled: false,
  },
];

export default pricingData;
